name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Labo0

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Créer fichier .env 
        run: |
          echo "CALCULATOR_USERNAME=GithubActions" >> .env

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Éxécuter les tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: | 
          python -m pytest 

  second_build:
    runs-on: self-hosted  
    needs: build          
    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3
      - name: Build de l'image
        run: docker build -t calculatrice .

      - name: Supprimer conteneur existant
        run: |
          docker stop labo0log430 || true
          docker rm labo0log430 || true

      - name: Lancer le conteneur
        run: docker run -d -p 5000:5000 --name labo0log430 calculatrice

      - name: Vérification du déploiement
        run: |
          sleep 2
          docker ps | grep labo0log430 || exit 1




